# Generated by Django 4.2.1 on 2024-03-01 10:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_alter_product_lesson'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='date_created',
            new_name='date_create',
        ),
    ]
