# Generated by Django 4.2.1 on 2024-03-01 11:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0006_product_lesson'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='lesson',
        ),
    ]
