# Generated by Django 4.2.1 on 2024-03-01 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0008_product_lesson'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='lesson',
        ),
        migrations.AddField(
            model_name='product',
            name='lesson',
            field=models.ManyToManyField(null=True, related_name='lesson', to='product.lesson'),
        ),
    ]
