# Generated by Django 4.2.1 on 2024-03-02 10:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0019_alter_lesson_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lessons', to='product.product'),
        ),
        migrations.AlterField(
            model_name='product',
            name='date_start',
            field=models.DateField(verbose_name='Дата старта'),
        ),
    ]
