# Generated by Django 4.2.1 on 2024-03-02 19:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('product', '0020_alter_lesson_product_alter_product_date_start'),
    ]

    operations = [
        migrations.RenameField(
            model_name='group',
            old_name='title',
            new_name='name',
        ),
        migrations.AddField(
            model_name='group',
            name='product',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='product.product'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='max_users',
            field=models.PositiveSmallIntegerField(default=5, verbose_name='Макс.кол-во участников в группе'),
        ),
        migrations.AddField(
            model_name='product',
            name='min_users',
            field=models.PositiveSmallIntegerField(default=1, verbose_name='Мин.кол-во участников в группе'),
        ),
        migrations.CreateModel(
            name='ProductAccess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_paid', models.BooleanField(default=False, verbose_name='Оплачен')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.product')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Доступ к продукту',
                'verbose_name_plural': 'Доступы к продуктам',
            },
        ),
    ]
